

/* 
CRIAÇÃO DE VIEWS:

É UMA JUNÇÃO DE  VÁRIAS TABELAS EM UMA SÓ

VOCÊ PEGA VÁRIAS TABELAS E FAZ UMA VIEWS QUE É JUNTAR TODAS EM UMA SÓ
TEM UMA PERFOMANCE MELHOR

NÃO PESA COMO UMA TABELA POIS FICA ARMAZENADO EM SISTEMA 

CONSOLIDA INFORMAÇÕES DE VÁRIAS TABELAS EM UM ÚNICO SELECT 

OTIMIZAÇÃO DAS CONSULTAS 
*/

-- CRIANDO A VIEW
CREATE VIEW VW_RELATORIO  AS 
SELECT*
FROM RELATORIO_NOVO

-- CONSULTANDO A VIEW
SELECT*
FROM VW_RELATORIO
