
----UPDATE
SELECT *
FROM TB_VENDAS
WHERE VENDEDOR = 'LUIZ LOPES'
-- BEGIN TRAN 
-- ROLLABACK
-- COMMIT

BEGIN TRAN						-- RODANDO SO O BEGIN TRAN FICA UMA TRAVA E COM O COMMIT LIBERA PARA CONSULTAS
UPDATE TB_VENDAS				-- TABELA PARA SER ALTERADA 
SET VENDEDOR = 'LUIZ LOPES'		-- CAMPO/ COLUNA PARA SER ALTERADO
WHERE VENDEDOR = 'LLP'			-- ONDE FOR LLP

COMMIT		-- LIBERA OS DADOS PARA CONSULTAR 