
-- CONCAT (CONCATENAR/JUNTAR)
SELECT CONCAT ('SQL','MODULO', 'I')

-- CONCATENOU/JUNTOU A COLUNA DE ESTADOS COM UF PARA OTIMIZAR E COLOQUEI UM NOVO NOME DE NOVA_COLUNA 
SELECT CONCAT( estados, '-',UF) AS NOVA_COLUNA
FROM tb_netflix