
/*
EXERCICIO

Criar um banco CONTROLE_GERAL
Ciar 3 tabelas
Inserir 5 registros para cada tabela
Todas as tabelas com ID INT IDENTITY, não podendo ser nenhum campo NULL

ESTOQUE		- QUANTIDADE, NOME_PRD, DISPONIVEL, NUMERO_DA_NOTA
VENDAS		- VALOR, PROD, QUANTIDADE, VENDEDOR, FILIAL 
CLIENTES	- NOME, CPF, ENDERECO, SEXO, CIDADE

*/ 

-- CRIANDO O BANCO DE DADOS CONTROLE_GERAL
CREATE DATABASE CONTROLE_GERAL

-- CRIANDO A TABELA ESTOQUE
CREATE TABLE ESTOQUE 
(
	ID INT IDENTITY (1,1),
	QUANTIDADE INT ,
	NOME_PROD  varchar (255),
	DISPONIVEL varchar (255),
	NUMERO_DA_NOTA INT 
)

SELECT *
FROM ESTOQUE


-- INSERINDO OS VALORES NA TABELA ESTOQUE
INSERT INTO ESTOQUE
VALUES 
(10,'CAMISA', 'SIM', '120260001'),
(50,'VESTIDO','NÃO', '220260001'),
(30,'SHORT', 'SIM', '320260001'),
(20,'SAIA', 'SIM', '420260001'),
(40,'REGATA', 'SIM', '520260001')



-- CRIANDO A TABELA VENDA 
 CREATE TABLE VENDA
 (
	VALOR int,
	PROD varchar (255),
	QUANTIDADE int ,
	VENDEDOR varchar (255),
	FILIAL varchar (255)
 )

 -- CONSULTANDO A TABELA VENDA CRIADA
 SELECT*
 FROM VENDA


 -- ISERINDO OS DADOS NA TABELA VENDA
INSERT INTO VENDA
 VALUES 
 (30, 'CAMISA', 10, 'CLARA', 'RIO DE JANEIRO'),
 (40, 'VESTIDO', 20, 'LETICIA', 'SAO PAULO'),
 (50, 'SHORT', 11, 'MARIANA', 'SAO PAULO'),
 (35,'VESTIDO', 22, 'ADRIAIA', 'MINAS GERAIS'),
 (50,'REGATA', 15, 'SANDRA', 'MINAS GERAIS')

 -- CRIANDO A TABLE CLIENTES
 CREATE TABLE CLIENTES 
 (
	NOME varchar (255),
	CPF varchar (255),
	ENDERECO varchar (255),
	SEXO varchar (255),
	CIDADE varchar (255),
 ) 

 -- CONSULTANDO A TABELA CLIENTES 
 SELECT *
 FROM CLIENTES

 -- INSERINDO OS DADOS NA TABELA CLIENTES
 INSERT INTO CLIENTES
 VALUES
 ('HENRICO', '12320878920', 'RUA SETE DE SETEMBRO', 'MASCULINO', 'BRASILIA'),
 ('CECILIA', '13587598710', 'RUA NOVE DE JULHO', 'FEMININO', 'RIO DE JANEIRO'),
 ('CLARA', '12389654700', 'RUA ONZE DE DEZEMBRO', 'FEMININO', 'JUIZ DE FORA'),
 ('ANTONIO', '54896512500', 'RUA OITO DE MAIO', 'MASCULINO', 'SAO PAULO'),
 ('RODRIGO', '25456987445', 'RUA TRES DE ABRIL', 'MASCULINO', 'SAO PAULO')
