

-- EXERCICIO 1
SELECT *
FROM tb_netflix

SELECT 
	TOTAL_USUARIOS AS [ACESSOS TOTAL],
	TIPO_DE_CONTA AS CONTA,
	VALOR		AS [VALOR DE VENDA],
	ESTADOS		 AS LOCAIS
FROM tb_netflix
WHERE PERIODO_DE_ACESS = 'MANHA'


-- EXERCICIO 2
SELECT
		TOTAL_USUARIOS AS [ACESSOS TOTAL],
		TIPO_DE_CONTA  AS CONTA,
		VALOR		   AS [VALOR DE MERCADO],
		ESTADOS		   AS REGIOES,
		DATA		   AS [PERIODO],
		UF
FROM tb_netflix
WHERE TOTAL_USUARIOS IN ('8480','997','4162', '241', '3656')


