
-- TRATANDO OS ARQUIVOS 
	SELECT
			RTRIM(NOME)					AS NOME,
			RTRIM(COD_CLI)				AS CLIENTE,
			RTRIM(ENDERECO)				AS ENDERECO,
			RTRIM(CPF)					AS CPF,
			RTRIM(CIDADE)				AS CIDADE,
			RTRIM(TIPO_DE_CLIENTE)		AS PERFIL
	FROM TB_CLIENTES


--CRIANDO UMA VIEW
CREATE VIEW RELATORIO_CLIENTES AS 

SELECT
			RTRIM(NOME)					AS NOME,
			RTRIM(COD_CLI)				AS CLIENTE,
			RTRIM(ENDERECO)				AS ENDERECO,
			RTRIM(CPF)					AS CPF,
			RTRIM(CIDADE)				AS CIDADE,
			RTRIM(TIPO_DE_CLIENTE)		AS PERFIL
	FROM TB_CLIENTES

--CONSULTANDO A VIEW CRIADA
SELECT*
FROM RELATORIO_CLIENTES
