
-- CRIAÇÃO DE TABELA VIRTUAL COM TABELA FÍSICA

-- CRIANDO A TABELA VIRTUAL
CREATE TABLE RELATORIO_NOVO
(
	FILIAL			INT,
	TICKET			INT,
	DATA			DATE,
	CLIENTE			VARCHAR(255),
	COLABORADOR		VARCHAR(255),
	QUANTIDADE		INT,
	VENDA			DECIMAL(18,2),
	PAGO			DECIMAL(18,2),
	CANCELADO		DECIMAL (18,2)
)
-- INSERINDO PARA A TABELA A CIMA 
INSERT INTO RELATORIO_NOVO
-- SELECT QUE IRA PARA A A NOVA TABELA 
SELECT 
	LOJA,
	CUPOM,
	DATA,
	COD_CLIENTE,
	VENDEDOR,
	QUANTIDADE,
	VALOR_VENDA,
	VALOR_PAGO,
	VALOR_CANCELADO
FROM TB_VENDAS

-- CONSULTANDO A TABELA CRIADA RELATORIO_NOVO
SELECT *
FROM RELATORIO_NOVO
