
SELECT *
FROM TB_VENDAS

-- CRIANDO UMA TABELA TEMPORÁRIA USAMOS UM (#)
SELECT*
INTO  #RELATORIO_LTZ
FROM TB_VENDAS
WHERE VENDEDOR = 'LTZ'	

-- CONSULTANDO A TABELA TEMPORÁRIA CRIADA USASMOS UM (#)
SELECT *
FROM #RELATORIO_LTZ

-- INSERINDO EM UMA TABELA TEMPORÁRIA CONSULTANDO EM OUTRA ABA/SESSÃO USAMOS DOIS (##)
SELECT *
INTO ##RELATORIO_LTZ
FROM TB_VENDAS
WHERE VENDEDOR = 'LTZ'